"""
blueprints/ems_negotiate_bp.py — EMS PWA SignalR Negotiate Endpoint
====================================================================
Route:   GET /api/ems-negotiate?bundleId={bundleId}
Purpose: Performs the SignalR handshake for EMS PWA clients, scoped to
         a specific patient bundle rather than to a hospital.

WHY userId=bundleId (Patient-Scoped Targeting):
    The hospital-facing negotiate endpoint (negotiate_bp.py) issues SignalR
    tokens with userId=hospitalId — grouping ALL dashboard connections for
    HUP-PAV under a single broadcast target. Any message sent to
    userId="HUP-PAV" reaches every nurse's workstation at that hospital.

    The EMS PWA operates differently: each medic device manages exactly ONE
    patient at a time. The medic needs to receive ONLY events for THEIR patient:
      • chatUpdate → new hospital message for bundle EMS-55-1709925600000
      • emsHandoffUpdate → hospital arrived/restored the patient

    If we used userId=medicUnit or userId=someGlobalId, two medics on unit 55
    could both receive events for each other's patients — a data isolation
    violation and a confusing UX where the wrong patient's messages appear.

    By issuing tokens with userId=bundleId (the unique patient encounter ID),
    the SignalR Service routes ONLY messages targeted at that specific bundleId
    to this connection. The EMS device for bundle EMS-55-001 will never receive
    a 'chatUpdate' meant for bundle EMS-42-002, even if both medics are
    connected to the same SignalR hub simultaneously.

EMS-Specific Validation (vs. negotiate_bp.py):
    hospital negotiate  → validates hospitalId against a 3-item allowlist
    ems negotiate       → validates bundleId is non-empty only

    WHY no bundleId allowlist:
    bundleId is a free-form string generated by the EMS PWA at form-submit
    time (e.g., "EMS-{unit}-{Date.now()}"). We cannot enumerate all valid
    bundleIds at the backend — they are dynamically created per patient
    encounter. The only security guarantee needed here is that the caller
    passes a non-empty bundleId so the issued token has a meaningful userId
    claim. The bundleId value itself is not a secret — it corresponds to a
    document in Cosmos DB whose access is already guarded by hospitalId
    partition isolation at every other endpoint.

Connection Lifecycle:
    ┌───────────────────────────────────────────────────────────────────┐
    │  1. EMS PWA submits patient (POST /api/ems-to-db)                 │
    │  2. bundleId stored in sessionStorage                             │
    │  3. GET /api/ems-negotiate?bundleId=EMS-55-1709925600000          │
    │  4. [This function] validates non-empty → issues signed token     │
    │  5. Returns: { "url": "wss://...", "accessToken": "eyJ..." }      │
    │  6. EMS SignalR client connects with userId=EMS-55-1709925600000  │
    │  7. Server broadcasts 'chatUpdate' to userId=bundleId             │
    │     → medic's ChatHub receives hospital messages in real time     │
    │  8. Server broadcasts 'emsHandoffUpdate' to userId=bundleId       │
    │     → medic notified when hospital arrives or restores patient    │
    └───────────────────────────────────────────────────────────────────┘

Security Design:
    - bundleId is validated as non-empty before the token is returned.
    - AzureSignalRConnectionString is shared with negotiate_bp.py —
      both EMS and hospital clients connect to the same EmsHandoff hub.
      Event routing isolation is enforced by the distinct userId values.
    - CORS headers are included for browser clients calling from the
      EMS SWA origin (different domain from the Function App).
"""

import json
import logging

import azure.functions as func

# =============================================================================
# Blueprint Instance
# =============================================================================

bp = func.Blueprint()

_HUB_NAME = "EmsHandoff"


# =============================================================================
# Route: GET /api/ems-negotiate
# =============================================================================


@bp.route(route="ems-negotiate", methods=["GET", "POST"], auth_level=func.AuthLevel.ANONYMOUS)
@bp.generic_input_binding(
    arg_name="connection_info",
    type="signalRConnectionInfo",
    hub_name=_HUB_NAME,
    # `{query.bundleId}` is an Azure Functions binding expression.
    # The Functions host resolves this at runtime by reading the `bundleId`
    # query parameter and embedding it as the `userId` claim in the signed
    # SignalR access token.
    #
    # Effect: The issued JWT has sub = "EMS-55-1709925600000" (or whichever
    # bundleId was requested). When arrival_bp.py broadcasts to
    # userId=bundle_id, SignalR Service matches on this sub claim and
    # delivers the push ONLY to this medic's connection.
    #
    # NOTE: The binding expression resolves BEFORE the function body
    # executes. Our validation below ensures we NEVER return a token for
    # an empty bundleId — the 400 response is returned instead.
    user_id="{query.bundleId}",
    connection="AzureSignalRConnectionString",
)
def ems_negotiate(
    req: func.HttpRequest,
    connection_info: str,
) -> func.HttpResponse:
    """
    HTTP-Triggered Azure Function: EMS PWA SignalR Negotiate Handshake.

    Issues a short-lived Azure SignalR Service access token scoped to the
    requesting patient bundle's userId (bundleId). The EMS SignalR client
    uses the returned URL and token to establish a direct WebSocket connection
    to Azure SignalR Service (serverless mode), receiving only events targeted
    at this specific patient bundle.

    ┌──────────────────────────────────────────────────────────────────────┐
    │  REQUEST                                                             │
    │  Method:  GET (POST also accepted for compatibility)                 │
    │  Route:   /api/ems-negotiate                                         │
    │  Query:   bundleId=EMS-55-1709925600000  (required, non-empty)      │
    └──────────────────────────────────────────────────────────────────────┘

    ┌──────────────────────────────────────────────────────────────────────┐
    │  RESPONSES                                                           │
    │  200 OK          { "url": "wss://...", "accessToken": "eyJ..." }    │
    │                  Client uses these to connect to SignalR Service.   │
    │  400 Bad Request Missing or empty bundleId query parameter.         │
    │                  No token is issued or returned.                    │
    └──────────────────────────────────────────────────────────────────────┘
    """
    bundle_id: str = req.params.get("bundleId", "").strip()

    # ── Validate bundleId — gate before returning connection info ─────────────
    # Unlike negotiate_bp.py which checks an allowlist, we only verify non-empty.
    # A token with an empty userId would create an anonymous SignalR connection
    # that could receive messages targeted at the empty-string userId — undesirable.
    if not bundle_id:
        logging.warning("ems-negotiate: Missing or empty bundleId query parameter.")
        return func.HttpResponse(
            body=json.dumps(
                {
                    "error": (
                        "Missing required query parameter: bundleId. "
                        "bundleId must be the patient encounter identifier "
                        "(e.g., 'EMS-55-1709925600000')."
                    )
                }
            ),
            status_code=400,
            mimetype="application/json",
        )

    # ── Return SignalR Connection Info ────────────────────────────────────────
    # `connection_info` is a JSON string produced by the signalRConnectionInfo
    # input binding containing { "url": "...", "accessToken": "eyJ..." }.
    # The EMS PWA's useEmsSignalR hook reads these values to build the
    # HubConnectionBuilder:
    #   .withUrl(info.url, { accessTokenFactory: () => info.accessToken })
    logging.info(
        "ems-negotiate: Issuing EMS SignalR token | bundleId=%s", bundle_id
    )

    return func.HttpResponse(
        body=connection_info,
        status_code=200,
        mimetype="application/json",
        headers={
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Credentials": "true",
        },
    )
